### Customer - get all

GET http://localhost:8020/api/v1/customers

### Customer - delete
DELETE localhost:8020/api/v1/customers/1

### Customer - add
POST localhost:8020/api/v1/customers
Content-Type: application/json

{
  "customerId": 1,
  "firstname": "chen",
  "lastname": "soul",
  "email": "ichensoul@gmail.com"
}

### Customer - get
GET localhost:8020/api/v1/customers/1

### Customer - exists
GET localhost:8020/api/v1/customers/exists/1


### Product - get all

GET http://localhost:8060/api/v1/products

### Order - find all
GET localhost:8040/api/v1/orders

### Order - Delete
DELETE localhost:8040/api/v1/orders/2

### Order - Create
POST localhost:8040/api/v1/orders
Content-Type: application/json

{
  "totalAmount": 99.99,
  "paymentMethod": "PAYPAL",
  "customerId": 1,
  "products": [
    {
      "productId": 1,
      "quantity": 1
    }
  ]
}

### Eureka
GET http://localhost:8761/eureka/apps
Accept: application/json
