FROM maven:3.9.9-eclipse-temurin-21-jammy AS build
WORKDIR /build
COPY . .
RUN mvn clean package

FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /build/target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]